name: Cypress Tests

on:
  push:
    branches:
      - main  # Ejecuta las pruebas en cada push a la rama 'main'
  pull_request:
    branches:
      - main  # Ejecuta las pruebas en cada pull request a la rama 'main'

jobs:
  test:
    runs-on: wondows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'  # Cambia la versión si tu proyecto usa otra

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
        env:
          # Configura la variable de entorno DISPLAY si usas algún comando que la requiera
          # Display es necesario en algunos proyectos que usan GUI con Cypress
          DISPLAY: ":99.0"
